### ISSUE TITLE
Number of notification show only on home page

### ISSUE THREAD

**Issue by Steph4104** [gctools-outilsgc/gccollab-mobile#108]
On home page, the user can see if they have some notification

![image](https://user-images.githubusercontent.com/15112568/37518696-9a0f5b88-28ec-11e8-8bb8-fa762c923380.png)

On every other page they have no indication

![image](https://user-images.githubusercontent.com/15112568/37518766-f5328a44-28ec-11e8-8c1b-d0f4ab8daa75.png)

**Comment by bmrgould** [comment]
N/A anymore
