### ISSUE TITLE
Bookmarks - Page, popup/view

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#16]
Bookmarks need to be added.

They need a page listing them all, with tabs for all, colleagues, and self.

Needs a popup for the bookmark itself.

**Comment by bmrgould** [comment]
Going to wait on post of what is left until api changes are done

**Comment by markwooff** [comment]
I’m reviewing the API changes now, should get them merged in today.

**Comment by bmrgould** [comment]
Documenting so it's written somewhere.

Elgg objects, such as bookmarks and files, when posted by a user to a group, will not show up on that user's profile. That is just how it currently works with the site. This is due to how container_guid is used and saved.

So for the mine tab of bookmarks, it will be the same.

**Comment by bmrgould** [comment]
Bookmarks page is complete. Link in the sidebar. 

Bookmarks page has three tabs loading correct bookmarks.

`Refresh` works. 3 separate `More` works.

`View` popup is complete. `View` works.

![bookmark](https://user-images.githubusercontent.com/34379222/36557239-bbc3bdfa-17d5-11e8-94ac-be868a8473ce.PNG)
![bookmarks](https://user-images.githubusercontent.com/34379222/36557240-bbd0bc8a-17d5-11e8-84ef-7c0ad65cc4ef.PNG)
