### ISSUE TITLE
Unable to login on App

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab-mobile#193]
User downloaded the GCcollab app on both  android smartphone & ipad but is unable to login;
Keeps getting the error message; "You have entered an invalid username or password."

User can log in on web browser successfully; then she attempted to log in on the ipad app again - very carefully validating that she entered the correct characters for both the email address and password - but, still no luck!

E-mail: ainslie.nolan@canada.ca
GCcollab username: Ainslienolan (validated)
https://gccollab.ca/profile/Ainslienolan
Single Sign-on Active

**Comment by KevinChagnon** [comment]
@markwooff @bmrgould

**Comment by KevinChagnon** [comment]
User: "Please let me know if you need me to do a test and provide any specific details or screen shots"

(user willing to work with us if testing or more information required)

**Comment by markwooff** [comment]
We may need to look into adding the same Single Sign-On that appears across the GCcollab service into the mobile app. Thinking this is most likely what is causing the issue, will be helpful to have this user confirm the fix for once we have it in place!

**Comment by KevinChagnon** [comment]
Does this mean you are working on implementing the Single Sign-on for the mobile app?

Will keep ticket open until this is in place and we are ready to have this user try again.

**Comment by markwooff** [comment]
That’s correct, I’ve actually finished building the Single Sign-On into the mobile app which will come out in the next release of the app. This new version should be coming at the end of this sprint.

**Comment by markwooff** [comment]
This issue has been resolved with the app now using the Single Sign-On to login 👍
