### ISSUE TITLE
Contact Us Page?

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#22]
Currently we have a help link called Contact / Feedback that goes to a default contact us page. Are we using this, removing it, or something else? Remove links to it, but leave it for possible future use?

![image](https://user-images.githubusercontent.com/15112568/36277742-bf571712-125f-11e8-8850-6f24bf930300.png)

![image](https://user-images.githubusercontent.com/15112568/36277851-13d79e06-1260-11e8-81c7-ce1b09e5da28.png)

**Comment by bmrgould** [comment]
If we don't end up doing something with this when the next release is ready, we should have the link go to the in-app browser of gccollab contact/help page: https://gccollab.ca/help/knowledgebase

**Comment by markwooff** [comment]
Agreed. This page had originally come with the app template and wasn't intended for use.
