### ISSUE TITLE
Add Social Sharing

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab-mobile#27]

**Comment by markwooff** [comment]
Will test using https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin PhoneGap plugin.

**Comment by markwooff** [comment]
Should now be added with https://github.com/gctools-outilsgc/gccollab-mobile/commit/34ff00fe5d7138f925ffb4f8a2f9c3d608174c97 - ready for testing @bmrgould
