### ISSUE TITLE
Group Members Page Error 

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#49]
Error on accessing group's members page. 

Happens on `GCcollab Jobs Marketplace` and `The Policy Community` so may be from the number of members they have. 
Does not happen on `Canada - Indigenous Relations:` which is the 3rd largest. 
Does happen on `GCcollab Group Owners' and Operators' Corner` the 4th largest. 
Does not happen on `Canada Beyond 150` the 5th largest.
Does not happen on `The Future of Government` the 6th largest.
Does happen on `GCcollab Café` the 7th largest.
Does happen on `Intelli: The Latest on Public Sector Innovation` the 8th largest.
Does not happen on `Social Innovation` the 9th largest.
Does happen to `Talent Cloud` the 10th largest.

`Uncaught TypeError: Cannot use 'in' operator to search for '47' in Group was not found. Please try a different GUID`

**Comment by bmrgould** [comment]
Current fix testing:

moving `if (!elgg_is_logged_in()) {
		login($user_entity);
	}`

to before the get_entity will make it work. This change might have to go for all the api functions.

**Comment by markwooff** [comment]
Yes I think you moved that line of code above in a different API call, correct? If that's the fix, then we should do for all API calls.
