### ISSUE TITLE
Zooming and scaling must not be disabled

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#55]
https://dequeuniversity.com/rules/axe/2.6/meta-viewport?application=AxeChrome

> The document must not use the user-scalable=no parameter in the <meta name="viewport"> element because it disables text scaling and zooming which is essential to users with low vision.

Also wants a max scale of at least 5.

Not sure on the impact of allowing zoom will cause on the app.

Looking at posts elsewhere, phonegap stuff might need to be changed to allow zoom as well.

**Comment by markwooff** [comment]
This isn't necessarily the case for mobile as native apps do not allow pinch/zoom by default. PhoneGap applications by default include the `user-scalable=no` (https://cordova.apache.org/docs/en/latest/config_ref/index.html).
