### ISSUE TITLE
User Profile Popup to Simple Sheet Modal

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#61]
With the full user page added, the popup will be changed to a sheet modal, and only show some basic information, and link to the user's full profile.

Gives the user the target users basic information without having to load their full profile.
Name, Job, Department, basic description.

https://framework7.io/docs/sheet-modal.html

**Comment by bmrgould** [comment]
Sheet Modal is a Framework 7 v2 addition. We are currently using v1 so we would have to migrate to v2 before doing this. 

Going to leave the function where it would open the sheet, but have it move straight to the full page profile. That way there is room to either do something else, or do this when on v2.

**Comment by Troy-Lawson** [comment]
any update on this card @bmrgould ?

**Comment by bmrgould** [comment]
Going to take a look after the current milestone is completed. Going to need to make sure it handles well for accessibility. Ill add it to the next milestone.

**Comment by bmrgould** [comment]
Accessibility for the sheet is similar to other on-page F7 components. Focus will need to be set on open/close to move Screen-reader and keyboard users to the correct html elements.

For implementing it, the data required is present in most (all?) entities with their UserDetails passed in with the api request.

**Comment by bmrgould** [comment]
Currently setup for only list wires, inside the User-Profile-Sheet branch, but looking like this:
![usersheet](https://user-images.githubusercontent.com/34379222/42584317-ef0c9b44-8500-11e8-823c-366cc51cdd6a.PNG)
