### ISSUE TITLE
Page onclick events persist on new instances of page

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#64]
Noticed while working on user profile activity, and can see happening on group profiles as well.

Going to a user or group page is always done through a link to view a specific user/group, and guid is added to url/header. The page is loaded for that group/user and filled based on that guid. With different tabs, it grabs information through API based on that guid. The ViewMore button for a tab has an onclick event added to load more content. 

Issue: Going to additional user/group pages and using the ViewMore will do api calls for both the new and old instance. So it's saving the onclick events through new instances of the page.

Look at: How the pages are currently being loaded, is it the best way for a dynamic/guid based page? Is there a simple clear/reset events? Does the current `myApp.onPageInit('page'` system need to be slit or moved into other framework7 functions that better suit the dynamic/guid based pages?

_Should be dealt with before moving more content to pages from popups._

**Comment by markwooff** [comment]
Agreed that this should be looked into before the heavy workload of moving everything from pop ups. There very well may be a better way of loading dynamic pages using F7 - have a look through their docs as they have tons of useful info there.

Curious.. does each View More button have an onclick attribute that calls the load more function? Or is a selector function that is binded to the click event? One might be better to use vs the other.

**Comment by bmrgould** [comment]
Currently the page content is generated inside the `myApp.onPageInit` for each page, which has a function to handle the content and appending to the html. Inside that we have a function for the ViewMore: 
```
$(document).on('click', '#user-activity-more', function (e) {
        GCTUser.GetUserActivity(guid, profile_limit, offset_activity + profile_limit, function (data3) {
            var activityData = data3.result;

            var activity = "";
            $(activityData).each(function (key, value) {
                var content = GCTEach.Activity(value);

                $(content).appendTo('#user-activity');
            });
            offset_activity += profile_limit;

        }, function (jqXHR, textStatus, errorThrown) {
            console.log(jqXHR, textStatus, errorThrown);
        });
    });
```

If it's adding the onclick event everytime, I could see about having the onclick always there so theres only one. Just need to make sure it reaches the variables it uses. GUID can be queried inside the onclick function. Limit can be hard coded. Just needs to keep track of the offset/reset the offset per user/group profile.

**Comment by bmrgould** [comment]
Testing simple fix, `$$('#user-activity-more').on('click', function (e) {` as everything else other than ViewMore uses that syntax and has no load/stacked events issues. Working so far.
