### ISSUE TITLE
Implementing Common Look and Feel / Consistent navigation

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#70]
Implement current planned look on `group` or user `profile pages` to test functionality and deal with any CSS or framework7 features needed. Get opinion on user experience.

Implement planned layout to all non-popup pages.

Move more objects towards dynamic/guid based pages and away from popups so we can use new layout.
1. Wire
2. Blog
3. Bookmark
4. Event
5. Opportunity
6. Discussion

**Comment by bmrgould** [comment]
Example of new layout:
![profile](https://user-images.githubusercontent.com/34379222/37104593-1dd3f670-21fb-11e8-9dc2-ba7e79099d6f.PNG)

Layout has been applied to all current pages, now popups need to be migrated into pages.

**Comment by markwooff** [comment]
Looks great @bmrgould !
