### ISSUE TITLE
End Of Content instead of No Matches for lists

### ISSUE THREAD

**Issue by bmrgould** [gctools-outilsgc/gccollab-mobile#73]
For listed content, such as a user's bookmarks, I think it makes more sense to say End of Content rather than No Matches. It also allows more flexibility about when we enter the card. By going with End of Content I can use a conditional to remove the View More button if the content received from API is less than we asked for.  This would remove the user clicking View More just to get a "No Matches" response. (Except in the situation where we content lines up perfectly with the limit)

**Comment by markwooff** [comment]
I think the wording of “No Matches” was originally intended for when filters returned no results. It makes sense in that context, but doesn’t work in the situation you bring up.

Could we use both but make sure they’re used in the right context? Thanks

**Comment by bmrgould** [comment]
Yeah, context is important. 

Looking at how many spots this needs to be done for each object, going to tackle it slowly between working on other things, as it's not urgent.
